# version: '3.8'

services:

  backend:
    build: .
    container_name: "expense-backend"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/expense_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      
  redis:
    image: redis:alpine
    container_name: expense-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  postgres:
    image: postgres:latest
    container_name: expense-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
 